### ISSUE TITLE
Punctuation Error in Week 2 Blog Post

### ISSUE THREAD

**Issue by deniceysv** [hunter-college-ossd-spr-2020/sdhani-weekly#2]
In the following sentence (located in the **A Good Place to Start**): 
*Since I already enjoy note-taking and stylizing, this goal seems to be up my alley, however it will be interesting to see what kinds of problems I may encounter in this arena.*

You should replace the comma after "my alley" with a semicolon.

Thus it should be: *Since I already enjoy note-taking and stylizing, this goal seems to be up my alley; however it will be interesting to see what kinds of problems I may encounter in this arena.*

**Comment by sdhani** [comment]
accepted changes
